#
# Makefile for the Cavium Octeon specific kernel interface routines
# under Linux.
#
# This file is subject to the terms and conditions of the GNU General Public
# License.  See the file "COPYING" in the main directory of this archive
# for more details.
#
# Copyright (C) 2005-2008 Cavium Networks
#

obj-y += cvmx-bootmem.o cvmx-l2c.o cvmx-sysinfo.o octeon-model.o
obj-y += cvmx-spi.o \
	cvmx-helper-board.o \
	cvmx-interrupt-decodes.o cvmx-interrupt-rsl.o \
	cvmx-global-resources.o \
	cvmx-range.o \
	cvmx-qlm.o

obj-y += cvmx-helper-errata.o cvmx-helper-jtag.o cvmx-boot-vector.o
